"""add_check_in_comments_and_likes

Revision ID: 1884681547e4
Revises: aee692a34f0b
Create Date: 2025-08-20 16:32:22.110307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1884681547e4'
down_revision = 'aee692a34f0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('check_in_comments_user_id_fkey'), 'check_in_comments', type_='foreignkey')
    op.drop_constraint(op.f('check_in_comments_check_in_id_fkey'), 'check_in_comments', type_='foreignkey')
    op.create_foreign_key(None, 'check_in_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'check_in_comments', 'check_ins', ['check_in_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_check_in_like'), 'check_in_likes', type_='unique')
    op.create_unique_constraint('uq_checkin_like', 'check_in_likes', ['check_in_id', 'user_id'])
    op.drop_constraint(op.f('check_in_likes_user_id_fkey'), 'check_in_likes', type_='foreignkey')
    op.drop_constraint(op.f('check_in_likes_check_in_id_fkey'), 'check_in_likes', type_='foreignkey')
    op.create_foreign_key(None, 'check_in_likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'check_in_likes', 'check_ins', ['check_in_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'check_in_likes', type_='foreignkey')
    op.drop_constraint(None, 'check_in_likes', type_='foreignkey')
    op.create_foreign_key(op.f('check_in_likes_check_in_id_fkey'), 'check_in_likes', 'check_ins', ['check_in_id'], ['id'])
    op.create_foreign_key(op.f('check_in_likes_user_id_fkey'), 'check_in_likes', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_checkin_like', 'check_in_likes', type_='unique')
    op.create_unique_constraint(op.f('uq_check_in_like'), 'check_in_likes', ['check_in_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'check_in_comments', type_='foreignkey')
    op.drop_constraint(None, 'check_in_comments', type_='foreignkey')
    op.create_foreign_key(op.f('check_in_comments_check_in_id_fkey'), 'check_in_comments', 'check_ins', ['check_in_id'], ['id'])
    op.create_foreign_key(op.f('check_in_comments_user_id_fkey'), 'check_in_comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
