"""reviews and my_checkins

Revision ID: 31d536d92ca5
Revises: 90bfafc9d11a
Create Date: 2025-08-19 12:06:06.926067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d536d92ca5'
down_revision = '90bfafc9d11a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
