"""add_dm_pin_archive_and_notification_prefs

Revision ID: 3592bf431989
Revises: 1884681547e4
Create Date: 2025-08-20 17:00:02.487112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3592bf431989'
down_revision = '1884681547e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dm_participant_states', sa.Column('pinned', sa.Boolean(), nullable=True))
    op.add_column('dm_participant_states', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dm_participant_states', 'archived')
    op.drop_column('dm_participant_states', 'pinned')
    # ### end Alembic commands ###
