"""Add updated_at field to dm_messages table

Revision ID: 38ac4358ad74
Revises: c8d49e842d05
Create Date: 2025-09-27 12:12:09.803313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ac4358ad74'
down_revision = 'c8d49e842d05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dm_messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dm_messages', 'updated_at')
    # ### end Alembic commands ###
