"""add_check_in_comments_and_likes

Revision ID: 3c2a8083e429
Revises: 845182146eb3
Create Date: 2025-08-20 14:43:04.829297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c2a8083e429'
down_revision = '845182146eb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendships_addressee_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_requester_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_constraint(op.f('uq_dm_message_likes_message_user'), 'dm_message_likes', type_='unique')
    op.create_index(op.f('ix_dm_message_likes_id'), 'dm_message_likes', ['id'], unique=False)
    op.create_index(op.f('ix_dm_messages_id'), 'dm_messages', ['id'], unique=False)
    op.alter_column('dm_participant_states', 'muted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('dm_participant_states', 'blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('uq_dm_participant_states_thread_user'), 'dm_participant_states', type_='unique')
    op.create_index(op.f('ix_dm_participant_states_id'), 'dm_participant_states', ['id'], unique=False)
    op.create_index(op.f('ix_dm_threads_id'), 'dm_threads', ['id'], unique=False)
    op.drop_constraint(op.f('uq_follows_pair'), 'follows', type_='unique')
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.create_unique_constraint(op.f('uq_follows_pair'), 'follows', ['follower_id', 'followee_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_dm_threads_id'), table_name='dm_threads')
    op.drop_index(op.f('ix_dm_participant_states_id'), table_name='dm_participant_states')
    op.create_unique_constraint(op.f('uq_dm_participant_states_thread_user'), 'dm_participant_states', ['thread_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('dm_participant_states', 'blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('dm_participant_states', 'muted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_dm_messages_id'), table_name='dm_messages')
    op.drop_index(op.f('ix_dm_message_likes_id'), table_name='dm_message_likes')
    op.create_unique_constraint(op.f('uq_dm_message_likes_message_user'), 'dm_message_likes', ['message_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_table('friendships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('addressee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], name=op.f('friendships_addressee_id_fkey')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('friendships_requester_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('friendships_pkey'))
    )
    op.create_index(op.f('ix_friendships_requester_id'), 'friendships', ['requester_id'], unique=False)
    op.create_index(op.f('ix_friendships_id'), 'friendships', ['id'], unique=False)
    op.create_index(op.f('ix_friendships_addressee_id'), 'friendships', ['addressee_id'], unique=False)
    # ### end Alembic commands ###
