"""Add external data fields to Place model

Revision ID: 56c02a011375
Revises: 3592bf431989
Create Date: 2025-08-24 03:36:22.724221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c02a011375'
down_revision = '3592bf431989'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column(
        'external_id', sa.String(), nullable=True))
    op.add_column('places', sa.Column(
        'data_source', sa.String(), nullable=True))
    op.add_column('places', sa.Column('website', sa.String(), nullable=True))
    op.add_column('places', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('places', sa.Column('metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_places_external_id'),
                    'places', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_external_id'), table_name='places')
    op.drop_column('places', 'metadata')
    op.drop_column('places', 'phone')
    op.drop_column('places', 'website')
    op.drop_column('places', 'data_source')
    op.drop_column('places', 'external_id')
    # ### end Alembic commands ###
