"""add_activity_feed_table

Revision ID: 592da07b0db4
Revises: 3c2a8083e429
Create Date: 2025-08-20 15:19:47.858389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592da07b0db4'
down_revision = '3c2a8083e429'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('message', sa.Text(), nullable=False))
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.drop_constraint(op.f('support_tickets_user_id_fkey'), 'support_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'support_tickets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('support_tickets', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('support_tickets_user_id_fkey'), 'support_tickets', 'users', ['user_id'], ['id'])
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.drop_column('support_tickets', 'message')
    # ### end Alembic commands ###
