"""add postal_code to places

Revision ID: add_postal_code
Revises: b2f3c52c4da3
Create Date: 2025-09-27 00:47:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_postal_code'
down_revision = 'b2f3c52c4da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('postal_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'postal_code')
    # ### end Alembic commands ###