"""add_onboarding_phone_username

Revision ID: aee692a34f0b
Revises: 592da07b0db4
Create Date: 2025-08-20 15:32:04.413134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee692a34f0b'
down_revision = '592da07b0db4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('otp_codes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.alter_column('otp_codes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('otp_codes', 'phone')
    # ### end Alembic commands ###
