"""add_user_blocks_table

Revision ID: bf6385c3c86e
Revises: 99ab7b0970fb
Create Date: 2025-09-19 22:06:30.900163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6385c3c86e'
down_revision = '99ab7b0970fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
