"""update_friendship_updated_at_default

Revision ID: c2c291470184
Revises: f72fff224f2c
Create Date: 2025-08-19 14:44:32.446570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c291470184'
down_revision = 'f72fff224f2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
