"""Add last_enriched_at to Place model

Revision ID: e29f38437e12
Revises: 56c02a011375
Create Date: 2025-08-24 03:55:28.898528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e29f38437e12'
down_revision = '56c02a011375'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('last_enriched_at',
                  sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'last_enriched_at')
    # ### end Alembic commands ###
