#!/usr/bin/env python3
"""
Flow Diagram Generator for Circles Application
Generates ASCII flow diagrams for request flows
"""

import os
import sys


def generate_general_flow():
    """Generate general request flow diagram"""
    print("🔄 GENERAL REQUEST FLOW")
    print("=" * 60)
    print()
    print("┌─────────────┐")
    print("│   CLIENT    │")
    print("│   REQUEST   │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│   FASTAPI   │")
    print("│ APPLICATION │")
    print("│  (main.py)  │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ MIDDLEWARE  │")
    print("│    STACK    │")
    print("│  (CORS, Log,│")
    print("│    Error)   │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│   ROUTER    │")
    print("│  MATCHING   │")
    print("│ (auth, users│")
    print("│  places...) │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│DEPENDENCY   │")
    print("│ INJECTION   │")
    print("│ (auth, db)  │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│  REQUEST    │")
    print("│ VALIDATION  │")
    print("│ (Pydantic)  │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│  BUSINESS   │")
    print("│   LOGIC     │")
    print("│ (Service)   │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│  DATABASE   │")
    print("│ OPERATIONS  │")
    print("│ (SQLAlchemy)│")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│  RESPONSE   │")
    print("│SERIALIZATION│")
    print("│ (Pydantic)  │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│   CLIENT    │")
    print("│  RESPONSE   │")
    print("└─────────────┘")
    print()


def generate_auth_flow():
    """Generate authentication flow diagram"""
    print("🔐 AUTHENTICATION FLOW")
    print("=" * 60)
    print()
    print("┌─────────────┐    ┌─────────────┐")
    print("│   CLIENT    │    │   CLIENT    │")
    print("│ REQUEST OTP │    │ VERIFY OTP  │")
    print("└──────┬──────┘    └──────┬──────┘")
    print("       │                  │")
    print("       ▼                  ▼")
    print("┌─────────────┐    ┌─────────────┐")
    print("│  RATE LIMIT │    │  RATE LIMIT │")
    print("│    CHECK    │    │    CHECK    │")
    print("└──────┬──────┘    └──────┬──────┘")
    print("       │                  │")
    print("       ▼                  ▼")
    print("┌─────────────┐    ┌─────────────┐")
    print("│ OTP GENERATE│    │ OTP VERIFY  │")
    print("└──────┬──────┘    └──────┬──────┘")
    print("       │                  │")
    print("       ▼                  ▼")
    print("┌─────────────┐    ┌─────────────┐")
    print("│ EMAIL SEND  │    │ USER CREATE │")
    print("└──────┬──────┘    │   /GET      │")
    print("       │           └──────┬──────┘")
    print("       ▼                  │")
    print("┌─────────────┐           ▼")
    print("│ DB STORE    │    ┌─────────────┐")
    print("│ (OTPCode)   │    │ JWT GENERATE│")
    print("└──────┬──────┘    └──────┬──────┘")
    print("       │                  │")
    print("       ▼                  ▼")
    print("┌─────────────┐    ┌─────────────┐")
    print("│  RESPONSE   │    │  RESPONSE   │")
    print("│ 'OTP sent'  │    │ JWT Token   │")
    print("└─────────────┘    └─────────────┘")
    print()


def generate_protected_endpoint_flow():
    """Generate protected endpoint flow diagram"""
    print("🛡️ PROTECTED ENDPOINT FLOW")
    print("=" * 60)
    print()
    print("┌─────────────┐")
    print("│   CLIENT    │")
    print("│ GET /users/me│")
    print("│ + Auth Header│")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ JWT EXTRACT │")
    print("│ & VALIDATE  │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ USER LOOKUP │")
    print("│ (Database)  │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ PERMISSION  │")
    print("│    CHECK    │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ BUSINESS    │")
    print("│   LOGIC     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ DB QUERY    │")
    print("│ (if needed) │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ SERIALIZE   │")
    print("│ RESPONSE    │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│   CLIENT    │")
    print("│  RESPONSE   │")
    print("└─────────────┘")
    print()


def generate_websocket_flow():
    """Generate WebSocket flow diagram"""
    print("🔌 WEBSOCKET FLOW")
    print("=" * 60)
    print()
    print("┌─────────────┐")
    print("│   CLIENT    │")
    print("│ WebSocket   │")
    print("│ /ws/dms/{id}│")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ TOKEN VALID │")
    print("│ (JWT)       │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ THREAD ACCESS│")
    print("│ VALIDATION  │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ CONNECTION  │")
    print("│ MANAGER     │")
    print("│ REGISTER    │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ WEBSOCKET   │")
    print("│ ACCEPT      │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ PRESENCE    │")
    print("│ BROADCAST   │")
    print("└─────────────┘")
    print()
    print("📨 MESSAGE FLOW:")
    print("┌─────────────┐")
    print("│ CLIENT MSG  │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ MSG VALIDATE│")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ DB STORE    │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ CONCURRENT  │")
    print("│ BROADCAST   │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ ALL USERS   │")
    print("│ RECEIVE MSG │")
    print("└─────────────┘")
    print()


def generate_file_upload_flow():
    """Generate file upload flow diagram"""
    print("📁 FILE UPLOAD FLOW")
    print("=" * 60)
    print()
    print("┌─────────────┐")
    print("│   CLIENT    │")
    print("│ Multipart   │")
    print("│ Form Data   │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ JWT AUTH    │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ FILE VALID  │")
    print("│ (type, size)│")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ IMAGE PROC  │")
    print("│ (Pillow)    │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ STORAGE     │")
    print("│ BACKEND     │")
    print("│ (S3/Local)  │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ ASYNC STORE │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ DB UPDATE   │")
    print("│ (file URL)  │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│  RESPONSE   │")
    print("│ Updated URL │")
    print("└─────────────┘")
    print()


def generate_database_flow():
    """Generate database operation flow diagram"""
    print("🗄️ DATABASE OPERATION FLOW")
    print("=" * 60)
    print()
    print("READ OPERATION:")
    print("┌─────────────┐")
    print("│ SERVICE     │")
    print("│ REQUEST     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ SESSION     │")
    print("│ CREATE      │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ QUERY BUILD │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ EXECUTE     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ PROCESS     │")
    print("│ RESULTS     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ SESSION     │")
    print("│ CLEANUP     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ RETURN      │")
    print("│ DATA        │")
    print("└─────────────┘")
    print()
    print("WRITE OPERATION:")
    print("┌─────────────┐")
    print("│ SERVICE     │")
    print("│ REQUEST     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ SESSION     │")
    print("│ CREATE      │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ MODEL       │")
    print("│ CREATE/UPDATE│")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ SESSION ADD │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ COMMIT      │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ REFRESH     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ CLEANUP     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ RETURN      │")
    print("│ UPDATED     │")
    print("└─────────────┘")
    print()


def generate_error_flow():
    """Generate error handling flow diagram"""
    print("❌ ERROR HANDLING FLOW")
    print("=" * 60)
    print()
    print("┌─────────────┐")
    print("│ EXCEPTION   │")
    print("│ OCCURS      │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ EXCEPTION   │")
    print("│ CAPTURE     │")
    print("│ (try/catch) │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ ERROR LOG   │")
    print("│ (logger)    │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ ERROR       │")
    print("│ CLASSIFY    │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ HTTP STATUS │")
    print("│ ASSIGN      │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ ERROR       │")
    print("│ RESPONSE    │")
    print("│ CREATE      │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ MIDDLEWARE  │")
    print("│ PROCESS     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ CLIENT      │")
    print("│ ERROR       │")
    print("│ RESPONSE    │")
    print("└─────────────┘")
    print()


def generate_rate_limiting_flow():
    """Generate rate limiting flow diagram"""
    print("⏱️ RATE LIMITING FLOW")
    print("=" * 60)
    print()
    print("┌─────────────┐")
    print("│ CLIENT      │")
    print("│ REQUEST     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ RATE LIMIT  │")
    print("│ CHECK       │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ COUNTER     │")
    print("│ UPDATE      │")
    print("│ (in-memory) │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ TIME WINDOW │")
    print("│ VALIDATE    │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ LIMIT       │")
    print("│ ENFORCE     │")
    print("└──────┬──────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐    ┌─────────────┐")
    print("│ ALLOWED?    │    │ BLOCKED?    │")
    print("└──────┬──────┘    └──────┬──────┘")
    print("       │                  │")
    print("       ▼                  ▼")
    print("┌─────────────┐    ┌─────────────┐")
    print("│ PROCESS     │    │ RATE LIMIT  │")
    print("│ REQUEST     │    │ RESPONSE    │")
    print("└──────┬──────┘    └─────────────┘")
    print("       │")
    print("       ▼")
    print("┌─────────────┐")
    print("│ NORMAL      │")
    print("│ RESPONSE    │")
    print("└─────────────┘")
    print()


def main():
    """Generate all flow diagrams"""
    print("🎯 CIRCLES APPLICATION - REQUEST FLOW DIAGRAMS")
    print("=" * 80)
    print()

    generate_general_flow()
    generate_auth_flow()
    generate_protected_endpoint_flow()
    generate_websocket_flow()
    generate_file_upload_flow()
    generate_database_flow()
    generate_error_flow()
    generate_rate_limiting_flow()

    print("📋 FLOW DIAGRAMS GENERATED SUCCESSFULLY!")
    print("=" * 80)
    print()
    print("These diagrams show the complete request flow through the Circles application.")
    print("Use them for debugging, optimization, and understanding system behavior.")
    print()
    print("For detailed documentation, see: docs/request_flow_documentation.md")


if __name__ == "__main__":
    main()
